/* eslint-disable */

const movies = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: '/PSBUyz5jXYqKr2OvLhQWmTbmSx.jpg',
      genre_ids: [99],
      id: 1015606,
      original_language: 'en',
      original_title: "Obi-Wan Kenobi: A Jedi's Return",
      overview:
        'A new documentary that showcases the making of the epic limited series. Features never-before-seen, behind-the-scenes footage, interviews and visits to the creature shop and props department.',
      popularity: 289.016,
      poster_path: '/wn6LkWQst96dPGEkn8Cl2TnNnLp.jpg',
      release_date: '2022-09-08',
      title: "Obi-Wan Kenobi: A Jedi's Return",
      video: false,
      vote_average: 7.7,
      vote_count: 78,
    },
    {
      adult: false,
      backdrop_path: '/4QLdZ2A8mkDWp2rpfgDrwmeCtUW.jpg',
      genre_ids: [28, 12, 80],
      id: 47971,
      original_language: 'en',
      original_title: 'xXx: Return of Xander Cage',
      overview:
        "Extreme athlete turned government operative Xander Cage comes out of self-imposed exile, thought to be long dead, and is set on a collision course with deadly alpha warrior Xiang and his team in a race to recover a sinister and seemingly unstoppable weapon known as Pandora's Box. Recruiting an all-new group of thrill-seeking cohorts, Xander finds himself enmeshed in a deadly conspiracy that points to collusion at the highest levels of world governments.",
      popularity: 128.55,
      poster_path: '/hba8zREJpP1AYhaXgb2oJLQeO0K.jpg',
      release_date: '2017-01-13',
      title: 'xXx: Return of Xander Cage',
      video: false,
      vote_average: 6,
      vote_count: 6684,
    },
    {
      adult: false,
      backdrop_path: '/dzgz0lXdDNOM78SepUHNcQHLhUZ.jpg',
      genre_ids: [14, 16, 878, 10751, 28],
      id: 8965,
      original_language: 'en',
      original_title: "Atlantis: Milo's Return",
      overview:
        'Milo and Kida reunite with their friends to investigate strange occurances around the world that seem to have links to the secrets of Atlantis.',
      popularity: 25.575,
      poster_path: '/c9siOypFgzsKL4LQI1d3EkDN6U3.jpg',
      release_date: '2003-02-25',
      title: "Atlantis: Milo's Return",
      video: false,
      vote_average: 6.3,
      vote_count: 2795,
    },
    {
      adult: false,
      backdrop_path: '/8rft8A9nH43IReybFtYt21ezfMK.jpg',
      genre_ids: [99],
      id: 899082,
      original_language: 'en',
      original_title: 'Harry Potter 20th Anniversary: Return to Hogwarts',
      overview:
        'An enchanting making-of story told through all-new in-depth interviews and cast conversations, inviting fans on a magical first-person journey through one of the most beloved film franchises of all time.',
      popularity: 112.159,
      poster_path: '/jntLBq0MLR3hrwKaTQswxACRPMs.jpg',
      release_date: '2022-01-01',
      title: 'Harry Potter 20th Anniversary: Return to Hogwarts',
      video: false,
      vote_average: 7.5,
      vote_count: 1986,
    },
    {
      adult: false,
      backdrop_path: '/1SeydkGlChbUrYJeV95TNSLQsFt.jpg',
      genre_ids: [16, 12, 35, 14],
      id: 125521,
      original_language: 'ja',
      original_title: 'スレイヤーズ RETURN',
      overview:
        "Lina Inverse and Naga the White Serpent are back! What begins as a routine bandit-stomping turns into the adventure of a lifetime involving magical golems, an ancient Elven weapon and even someone bent on destroying the world. It's a predicament only Lina and Naga could get themselves in to.",
      popularity: 12.74,
      poster_path: '/rDkod619OH3cWDAH3GwehFEx2Uu.jpg',
      release_date: '1996-08-03',
      title: 'Slayers Return',
      video: false,
      vote_average: 6.4,
      vote_count: 1289,
    },
    {
      adult: false,
      backdrop_path: '/kTtBDUeDZATzrTUlqHUG0ZWjg9m.jpg',
      genre_ids: [10752],
      id: 635744,
      original_language: 'en',
      original_title: 'Jarhead: Law of Return',
      overview:
        "Major Ronan Jackson, an accomplished fighter pilot for the Israel Defense Forces and son of a U.S. Senator, is shot down while flying through Syrian airspace. After miraculously surviving the crash, Jackson is taken captive by a group of Hezbollah militiamen. A squad of elite soldiers, led by Gunnery Sergeant Dave Torres, risk their own lives in the hopes of saving an ally they've never met.",
      popularity: 26.368,
      poster_path: '/6LlqyjAik3Kh68QQ9AchSJEF0Z5.jpg',
      release_date: '2019-10-01',
      title: 'Jarhead: Law of Return',
      video: false,
      vote_average: 6.5,
      vote_count: 2628,
    },
    {
      adult: false,
      backdrop_path: '/lXhgCODAbBXL5buk9yEmTpOoOgR.jpg',
      genre_ids: [12, 14, 28],
      id: 122,
      original_language: 'en',
      original_title: 'The Lord of the Rings: The Return of the King',
      overview:
        "Aragorn is revealed as the heir to the ancient kings as he, Gandalf and the other members of the broken fellowship struggle to save Gondor from Sauron's forces. Meanwhile, Frodo and Sam take the ring closer to the heart of Mordor, the dark lord's realm.",
      popularity: 212.454,
      poster_path: '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
      release_date: '2003-12-01',
      title: 'The Lord of the Rings: The Return of the King',
      video: false,
      vote_average: 8.5,
      vote_count: 20167,
    },
    {
      adult: false,
      backdrop_path: '/mOOJm3tamy9iHg2mOEA77CM6ufZ.jpg',
      genre_ids: [10751, 12, 16, 10749],
      id: 15969,
      original_language: 'en',
      original_title: 'The Return of Jafar',
      overview:
        "The evil Jafar escapes from the magic lamp as an all-powerful genie, ready to plot his revenge against Aladdin. From battling elusive villains atop winged horses, to dodging flames inside an exploding lava pit, it's up to Aladdin - with Princess Jasmine and the outrageously funny Genie by his side - to save the kingdom once and for all.",
      popularity: 34.835,
      poster_path: '/7SC793qtORB6YL4mu0F5o3hfjDQ.jpg',
      release_date: '1994-05-20',
      title: 'The Return of Jafar',
      video: false,
      vote_average: 6.1,
      vote_count: 2715,
    },
    {
      adult: false,
      backdrop_path: '/zldQJ1EhIc7G79cYyXrzQQzUl7a.jpg',
      genre_ids: [16, 28, 878, 14],
      id: 43641,
      original_language: 'en',
      original_title: 'Superman/Shazam!: The Return of Black Adam',
      overview:
        'Chosen the world’s protector against the Seven Deadly Enemies of Man – pride, envy, greed, hatred, selfishness, laziness and injustice – young Billy Batson accepts his destiny as Captain Marvel. Battling alongside Superman against nefarious Black Adam, Billy soon discovers the challenge super heroes ultimately face: is it revenge or justice?',
      popularity: 57.887,
      poster_path: '/3MgwChvi42N1RnhQE9A4pQVHyUY.jpg',
      release_date: '2010-11-16',
      title: 'Superman/Shazam!: The Return of Black Adam',
      video: false,
      vote_average: 7.3,
      vote_count: 630,
    },
    {
      adult: false,
      backdrop_path: '/poRKW1DNzNXfZQPPSGDVaRcwN7a.jpg',
      genre_ids: [10751, 10770, 16],
      id: 359983,
      original_language: 'en',
      original_title: 'The Lion Guard: Return of the Roar',
      overview:
        "Set in the African savannah, the film follows Kion as he assembles the members of the 'Lion Guard'. Throughout the film, the diverse team of young animals will learn how to utilize each of their unique abilities to solve problems and accomplish tasks to maintain balance within the Circle of Life, while also introducing viewers to the vast array of animals that populate the prodigious African landscape.",
      popularity: 64.41,
      poster_path: '/duqg6CiSik02nSXjiQHo8TcwY4b.jpg',
      release_date: '2015-11-22',
      title: 'The Lion Guard: Return of the Roar',
      video: false,
      vote_average: 6.5,
      vote_count: 983,
    },
    {
      adult: false,
      backdrop_path: '/zgLadRY6f8Ydgf9sKpiq3tPYBUM.jpg',
      genre_ids: [12, 28, 878],
      id: 1892,
      original_language: 'en',
      original_title: 'Return of the Jedi',
      overview:
        'Luke Skywalker leads a mission to rescue his friend Han Solo from the clutches of Jabba the Hutt, while the Emperor seeks to destroy the Rebellion once and for all with a second dreaded Death Star.',
      popularity: 28.723,
      poster_path: '/q6ydU8r1iYyy2bV7tPVaq266Y1k.jpg',
      release_date: '1983-05-25',
      title: 'Return of the Jedi',
      video: false,
      vote_average: 7.9,
      vote_count: 13220,
    },
    {
      adult: false,
      backdrop_path: '/nRCgF2ndHQ0vflGekeU4V2lufrF.jpg',
      genre_ids: [28, 878],
      id: 10366,
      original_language: 'en',
      original_title: 'Universal Soldier: The Return',
      overview:
        'Luc Deveraux, the heroic former Universal Soldier, is about to be thrown into action once again. When SETH, the supercomputer-controlled ultra-warrior, decides to take revenge and destroy its creators, only Luc can stop it. All hell breaks loose as Luc battles SETH and a deadly team of perfect soldiers in a struggle that pits man against machine and good against evil.',
      popularity: 20.646,
      poster_path: '/qlcPJK0Me8aUtDPwk3TqN2RdKH4.jpg',
      release_date: '1999-08-05',
      title: 'Universal Soldier: The Return',
      video: false,
      vote_average: 5.6,
      vote_count: 804,
    },
    {
      adult: false,
      backdrop_path: '/xxj9ajMDYQdBskD1KwEKRLqLlnS.jpg',
      genre_ids: [18, 53],
      id: 333381,
      original_language: 'en',
      original_title: 'Return to Sender',
      overview: 'A nurse living in a small town goes on a blind date with a man who is not the person he says he is.',
      popularity: 17.075,
      poster_path: '/idXlni6MEieEvRaDHxSPyeqP5pS.jpg',
      release_date: '2015-05-31',
      title: 'Return to Sender',
      video: false,
      vote_average: 6,
      vote_count: 959,
    },
    {
      adult: false,
      backdrop_path: '/14h57Khhp9hi11aJivH58u5tFyR.jpg',
      genre_ids: [35, 27],
      id: 10925,
      original_language: 'en',
      original_title: 'The Return of the Living Dead',
      overview:
        'When foreman Frank shows new employee Freddy a secret military experiment in a supply warehouse in Louisville, Kentucky, the two klutzes accidentally release a gas that reanimates corpses into flesh-eating zombies. As the epidemic spreads throughout the town, and the creatures satisfy their hunger in gory and outlandish ways, Frank and Freddy fight to survive with the help of their boss and a mysterious mortician.',
      popularity: 41.031,
      poster_path: '/mGv2YNs7SE1th18jwB0Ykju9G1W.jpg',
      release_date: '1985-04-25',
      title: 'The Return of the Living Dead',
      video: false,
      vote_average: 7.2,
      vote_count: 1458,
    },
    {
      adult: false,
      backdrop_path: '/ozIhpAb69vQahq5obDlRGP87Y0m.jpg',
      genre_ids: [99, 28, 12, 53],
      id: 503210,
      original_language: 'en',
      original_title: 'Return to Jurassic Park',
      overview:
        'A multi-part documentary about the making of the Jurassic Park trilogy. Each part walks through the making of part of one of the films, including the hurricane during the shooting of the first film, and how advances in CGI for Jurassic Park helped change the world of special effects forever. All interviews for these retrospective documentaries come with comments from Spielberg, Johnston, Neill, Dern, Goldblum, the effects crews, the child actors, and Peter Stormare. This documentary is broken into five parts: Dawn of a New Era (25 min) Making Prehistory (20 min), the Next Step in Evolution (15 min), and the Third Adventure (25 min), Finding the Lost World (28 min), and Something Survived (16 min).',
      popularity: 28.221,
      poster_path: '/mPyu59cDdmMDDW9IOtfjVlM0THd.jpg',
      release_date: '2011-02-05',
      title: 'Return to Jurassic Park',
      video: false,
      vote_average: 6.5,
      vote_count: 697,
    },
    {
      adult: false,
      backdrop_path: '/6jnSkRFKkcyKyQJGO5eVfFeXFGF.jpg',
      genre_ids: [10751, 16, 12],
      id: 283564,
      original_language: 'en',
      original_title: 'SlugTerra: Return of the Elementals',
      overview:
        'A new member has joined Eli and the Shane Gang! Junjie, once the protector of the Eastern Caverns, is a master of the slugslinging art of Slug Fu! But even with the power of five slingers, the Shane Gang find themselves in over their heads as they race across The 99 Caverns in search of the Legendary Elemental Slugs. The five Elementals are ancient slugs of great power, and the forbearers of all slugs found in SlugTerra today. In the wrong hands, they could bring Slugterra to the brink of destruction. So when an evil alliance starts hunting down the Elementals, Eli and his friends — old and new — take off in pursuit of the greatest threat their world has ever faced!',
      popularity: 29.25,
      poster_path: '/ApN2lteDsoIU5dDHJXeqVD13vpd.jpg',
      release_date: '2014-08-02',
      title: 'SlugTerra: Return of the Elementals',
      video: false,
      vote_average: 6.5,
      vote_count: 154,
    },
    {
      adult: false,
      backdrop_path: '/29cB9Ea6yO8OrE2r4e5fBcEo42f.jpg',
      genre_ids: [27, 53],
      id: 11357,
      original_language: 'en',
      original_title: 'Halloween 4: The Return of Michael Myers',
      overview:
        "The apparently comatose Michael Myers is being transferred from one hospital to another, but he wakes up when the ambulance crew talk about his surviving niece, Jamie. After slaughtering his attendants, Myers sets out to find his one living relative who is, fortunately, being cared for by a kind and resourceful foster sister named Rachel. Meanwhile, the ever-cautious Dr. Loomis remains on the killer's path.",
      popularity: 46.534,
      poster_path: '/iKbxhQa4T6zVY17RMa6AeiGEiSq.jpg',
      release_date: '1988-10-21',
      title: 'Halloween 4: The Return of Michael Myers',
      video: false,
      vote_average: 6.1,
      vote_count: 1261,
    },
    {
      adult: false,
      backdrop_path: '/meIF4dCPCh80gsBY5cM4E3jSKRd.jpg',
      genre_ids: [27],
      id: 708336,
      original_language: 'en',
      original_title: 'Return of the Tooth Fairy',
      overview:
        'The Tooth Fairy is back. 15 years after the events of the first movie, Corey, now grown up but mentally scarred has gone to a class reunion. However, the Tooth Fairy is back, and this time - You better have flossed properly.',
      popularity: 37.346,
      poster_path: '/n8XFS2FVStaBPS2vLqUuH2bAjVf.jpg',
      release_date: '2020-06-15',
      title: 'Return of the Tooth Fairy',
      video: false,
      vote_average: 6.5,
      vote_count: 809,
    },
    {
      adult: false,
      backdrop_path: '/5DJaUn1l9w1OaRYXzEkJBuFO5C2.jpg',
      genre_ids: [99],
      id: 950445,
      original_language: 'en',
      original_title: 'Return to Space',
      overview:
        "The inspirational rise of SpaceX as well as Elon Musk's two-decade effort to resurrect America’s space travel ambitions.",
      popularity: 18.825,
      poster_path: '/uyatxKGACzSNqDzTe5sv5YHAY30.jpg',
      release_date: '2022-04-07',
      title: 'Return to Space',
      video: false,
      vote_average: 6.2,
      vote_count: 450,
    },
    {
      adult: false,
      backdrop_path: '/dJ52jV7HlJ9hB8kdBOnj01DllBA.jpg',
      genre_ids: [18],
      id: 82520,
      original_language: 'en',
      original_title: 'Return',
      overview:
        'Back from a tour of duty, Kelli struggles to find her place in her family and the rust-belt town she no longer recognizes.',
      popularity: 8.354,
      poster_path: '/xAuR564U2njKKcXSbfbq36rZLeA.jpg',
      release_date: '2011-02-10',
      title: 'Return',
      video: false,
      vote_average: 6.7,
      vote_count: 486,
    },
  ],
  total_pages: 87,
  total_results: 1731,
};

let genre = {
  genres: [
    {
      id: 28,
      name: 'Action',
    },
    {
      id: 12,
      name: 'Adventure',
    },
    {
      id: 16,
      name: 'Animation',
    },
    {
      id: 35,
      name: 'Comedy',
    },
    {
      id: 80,
      name: 'Crime',
    },
    {
      id: 99,
      name: 'Documentary',
    },
    {
      id: 18,
      name: 'Drama',
    },
    {
      id: 10751,
      name: 'Family',
    },
    {
      id: 14,
      name: 'Fantasy',
    },
    {
      id: 36,
      name: 'History',
    },
    {
      id: 27,
      name: 'Horror',
    },
    {
      id: 10402,
      name: 'Music',
    },
    {
      id: 9648,
      name: 'Mystery',
    },
    {
      id: 10749,
      name: 'Romance',
    },
    {
      id: 878,
      name: 'Science Fiction',
    },
    {
      id: 10770,
      name: 'TV Movie',
    },
    {
      id: 53,
      name: 'Thriller',
    },
    {
      id: 10752,
      name: 'War',
    },
    {
      id: 37,
      name: 'Western',
    },
  ],
};

export { movies, genre };
